parserOptions:
  ecmaVersion: 2018
  sourceType: "module"
  allowImportExportEverywhere: true

settings:
  react:
    version: "detect"

env:
  es6: true
  browser: true
  commonjs: true
  jest: true
  node: true

rules:
  no-process-env: off
  no-invalid-this: 0
  babel/no-invalid-this: 1

parser: "babel-eslint"

extends: ["htmlacademy/es6", "plugin:react/recommended", "prettier"]

plugins:
  - "babel"
  - "prettier"
