parserOptions:
  ecmaVersion: 2018
  sourceType: 'module'
  allowImportExportEverywhere: true

settings:
  react:
    version: 'detect'

env:
  es6: true
  browser: true
  commonjs: true
  jest: true
  node: true

rules:
  no-process-env: off

extends: ['htmlacademy/es6', 'plugin:react/recommended']
